const express = require('express');
const router = express.Router();
const { createInvoice, getPatientInvoices, getDoctorInvoices, updateInvoiceStatus } = require('../controllers/invoiceController');
const auth = require('../middleware/auth');
const { authorize } = require('../middleware/role');

// Create a new invoice (doctors and admins)
router.post('/', auth, authorize('doctor', 'admin', 'super_admin'), createInvoice);

// Get invoices for logged-in patient
router.get('/patient', auth, authorize('patient'), getPatientInvoices);

// Get invoices generated by the logged-in doctor
router.get('/doctor', auth, authorize('doctor'), getDoctorInvoices);

// Update an invoice status
router.patch('/:id/status', auth, authorize('doctor', 'admin', 'super_admin', 'patient'), updateInvoiceStatus);

module.exports = router;
