const db = require('../config/db');

// Create a new invoice
exports.createInvoice = async (req, res) => {
    const { patient_id, appointment_id, amount, description } = req.body;

    try {
        let doctor_id = null;
        if (appointment_id) {
            const apptRes = await db.query('SELECT doctor_id FROM appointments WHERE id = $1', [appointment_id]);
            if (apptRes.rows.length > 0) {
                doctor_id = apptRes.rows[0].doctor_id;
            }
        }

        const newInvoice = await db.query(
            'INSERT INTO invoices (patient_id, doctor_id, appointment_id, amount, description) VALUES ($1, $2, $3, $4, $5) RETURNING *',
            [patient_id, doctor_id, appointment_id, amount, description]
        );

        res.status(201).json(newInvoice.rows[0]);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

// Get invoices for a patient
exports.getPatientInvoices = async (req, res) => {
    try {
        const invoices = await db.query(
            `SELECT i.*, d.full_name as doctor_name 
             FROM invoices i
             LEFT JOIN doctors doc ON i.doctor_id = doc.id
             LEFT JOIN users d ON doc.user_id = d.id
             WHERE i.patient_id = $1 
             ORDER BY i.created_at DESC`,
            [req.user.id] // req.user.id is the patient's user id
        );
        res.json(invoices.rows);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

// Get invoices generated by a specific doctor (or admin view)
exports.getDoctorInvoices = async (req, res) => {
    try {
        const doctorRes = await db.query('SELECT id FROM doctors WHERE user_id = $1', [req.user.id]);
        if (doctorRes.rows.length === 0) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const invoices = await db.query(
            `SELECT i.*, u.full_name as patient_name 
             FROM invoices i
             JOIN users u ON i.patient_id = u.id
             WHERE i.doctor_id = $1 
             ORDER BY i.created_at DESC`,
            [doctorRes.rows[0].id]
        );
        res.json(invoices.rows);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};

// Update invoice status (e.g. mark as paid)
exports.updateInvoiceStatus = async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;

    try {
        const updatedInvoice = await db.query(
            'UPDATE invoices SET status = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING *',
            [status, id]
        );

        if (updatedInvoice.rows.length === 0) {
            return res.status(404).json({ message: 'Invoice not found' });
        }

        res.json(updatedInvoice.rows[0]);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
};
